@extends('layouts.app')

@section('content')
<div class="sb-page-header pb-10 sb-page-header-dark bg-gradient-primary-to-secondary">
	<div class="container-fluid">
		<div class="sb-page-header-content py-5">
			<h1 class="sb-page-header-title">
				<div class="sb-page-header-icon"><i data-feather="key"></i></div>
				<span>{{ _lang('Merchant API') }}</span>
			</h1>
		</div>
	</div>
</div>

<div class="container-fluid mt-n10">
	<div class="row">
		<div class="col-lg-6">
			<div class="card">
				<div class="card-body">
				
					<div class="row">					 
					
						<div class="col-md-12">					 
							<div class="form-group">
								<label class="control-label"><b>{{ _lang('HTML FORM SMAPLE') }}</b></label><br>						
									<pre class="border pl-2">
										<code style="text-align: left; white-space: pre-line;">
										@php echo htmlspecialchars('<form action="'.route('checkout').'">
												<input type="hidden" name="business_email" value="'. Auth::user()->email .'"/>
												<input type="hidden" name="account_number" value="'. Auth::user()->accounts->first()->account_number .'"/>
												<input type="hidden" name="item_number" value="1001"/>
												<input type="hidden" name="item_name" value="T-Shirt"/>
												<input type="hidden" name="item_description" value="T-Shirt Blue"/>
												<input type="hidden" name="amount" value="10"/>
												<input type="hidden" name="custom1" value="Custom data 1"/>
												<input type="hidden" name="custom2" value="Custom data 2"/>
												<input type="hidden" name="success_url" value="https://yourwebsite.com/success.php"/>
												<input type="hidden" name="cancel_url" value="https://yourwebsite.com/cancel.php"/>
												<input type="hidden" name="notify_url" value="https://yourwebsite.com/notification.php"/>
												<input type="button" type="sucmit" value="Pay Now $10"/>
											</form>');
										@endphp
										</code>
									</pre>
								</code>
							</div>
						</div>	
					</div>	

				</div>
			</div>
		</div>
	</div>
    <br>
	
	<div class="row">
		
		<div class="col-lg-6">
			<div class="card">
				<div class="card-body">
				
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label class="control-label"><b>{{ _lang('Field Details') }}</b></label><br>
								<table class="table table-bordered">
									<thead>
										<tr>
											<th>{{ _lang('Field Name') }}</th>
											<th>{{ _lang('Required/Optionals') }}</th>
											<th>{{ _lang('Details') }}</th>
										</tr>
									</thead>
									
									<tbody>
										<tr>
											<td>business_email</td>
											<td>Required</td>
											<td>Your account email</td>
										</tr>
										<tr>
											<td>account_number</td>
											<td>Required</td>
											<td>Account Number use for taking user payment</td>
										</tr>
										<tr>
											<td>item_number</td>
											<td>Required</td>
											<td>Invoice number generated by your third party application</td>
										</tr>
										<tr>
											<td>item_name</td>
											<td>Required</td>
											<td>Item Name</td>
										</tr>
										<tr>
											<td>item_description</td>
											<td>Optional</td>
											<td>Item Description</td>
										</tr>
										<tr>
											<td>amount</td>
											<td>Required</td>
											<td>Amount</td>
										</tr>
										<tr>
											<td>custom1</td>
											<td>Optional</td>
											<td>Custom data 1</td>
										</tr>
										<tr>
											<td>custom2</td>
											<td>Optional</td>
											<td>Custom data 2</td>
										</tr>
										<tr>
											<td>success_url</td>
											<td>Required</td>
											<td>After making payment it will redirect to this URL</td>
										</tr>
										<tr>
											<td>cancel_url</td>
											<td>Required</td>
											<td>After clicking cancel payment it will redirect to this URL</td>
										</tr>
										<tr>
											<td>notify_url</td>
											<td>Optional</td>
											<td>After making payment it will notify this URL with payment data</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>	
					
				</div>					
			</div>					
		</div>

		
		<div class="col-lg-6">
			<div class="card">
				<div class="card-body">
				
					<div class="row">
						<div class="col-md-12">
							<div class="form-group">
								<label class="control-label"><b>{{ _lang('POST Notify Data') }}</b></label><br>
								<table class="table table-bordered">
									<thead>
										<tr>
											<th>{{ _lang('Field Name') }}</th>
											<th>{{ _lang('Details') }}</th>
										</tr>
									</thead>
									
									<tbody>
										<tr>
											<td>payer_first_name</td>
											<td>Payer First Name</td>
										</tr>
										<tr>
											<td>payer_last_name </td>
											<td>Payer Last Name</td>
										</tr>
										<tr>
											<td>payer_email</td>
											<td>Payer Email Address</td>
										</tr>
										<tr>
											<td>amount</td>
											<td>Payment Amount</td>
										</tr>
										<tr>
											<td>currency</td>
											<td>Currency</td>
										</tr>
										<tr>
											<td>item_number</td>
											<td>Item Number</td>
										</tr>
										<tr>
											<td>item_name</td>
											<td>Item Name</td>
										</tr>
										<tr>
											<td>item_description</td>
											<td>Item Description</td>
										</tr>
										<tr>
											<td>custom1</td>
											<td>Custome Data</td>
										</tr>
										<tr>
											<td>custom2</td>
											<td>Custome Data</td>
										</tr>
									</tbody>
								</table>
							</div>
						</div>
					</div>	
					
				</div>					
			</div>					
		</div>	
		
					
	</div>
</div>
@endsection

@section('js-script')
<script>
	$("#user_type").val("{{ old('user_type') }}");
</script>
@endsection


